# Generated by Django 6.0.2 on 2026-03-02 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_project_user_vote',
        ),
        migrations.AddField(
            model_name='project',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
