# Generated by Django 6.0.2 on 2026-03-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
    ]
