# Generated by Django 6.0.2 on 2026-03-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_category_created_at_remove_project_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
